### ISSUE TITLE
原神5.2无法识别已记录的出战牌组

### ISSUE THREAD

**Issue by RuibaiXu** [LumiOwO/LumiTracker#11]
**bug描述**
**Describe the bug**
当我更新原神到5.2后，启动记牌器，提示更新记牌器，我同意了记牌器的自动更新，然后使用已记录的卡组进入胜冠，发现无法识别卡组，尝试回退记牌器到1.2.10，也无法识别。

**如何复现**
**To Reproduce**
请简单描述如何复现这个问题
使用原神5.2尝试即可

**运行环境**
**Environment**
Win11 1920x1080窗口

**预期的正确表现**
**Expected behavior**
像2周前一样正常识别卡组

**Comment by RuibaiXu** [comment]
附上log

**Comment by RuibaiXu** [comment]
[error.log](https://github.com/user-attachments/files/17832599/error.log)

**Comment by LumiOwO** [comment]
5.2微调了起始界面的角色位置，导致角色识别不到了
等我周末更新~

**Comment by LumiOwO** [comment]
v1.2.12版本已修复~
