### ISSUE TITLE
希望能加入对于带鱼屏（21：9）的支持

### ISSUE THREAD

**Issue by Egoshell** [LumiOwO/LumiTracker#4]

**Comment by LumiOwO** [comment]
下个版本加21:9和16:10~

**Comment by LumiOwO** [comment]
查了一下发现21:9的屏幕比例竟然不统一。。
比如我在京东上搜到的几个分辨率：
3440x1440 (43:18)
2560x1080 (64:27)
3840x1600 (12:5)
5120x2160 (64:27)
求问下你的屏幕分辨率是多大的~

**Comment by LumiOwO** [comment]
看起来64:27、43:18、12:5都被算作21:9 （[维基百科](https://en.wikipedia.org/wiki/21:9_aspect_ratio#Computer_monitors)）
先支持这三个吧，没覆盖到的尺寸之后再解决

**Comment by Egoshell** [comment]
涨姿势了，我也才知道21：9还有这么多规格，我显示器是3440x1440的。up加油，希望能有更多人用你这个工具，实现成就-同人逼死官方hhhhh

**Comment by LumiOwO** [comment]
[v1.0.1](https://github.com/LumiOwO/LumiTracker/releases/tag/v1.0.1)已更新
