### ISSUE TITLE
[bug]无法正常识别对局

### ISSUE THREAD

**Issue by tiantianyigntao5** [LumiOwO/LumiTracker#7]
**bug描述**
无法识别对局中的过牌，衍生物等

**如何复现**
使用如下牌组进入对局：
FxAx0W0UF6EBlHwZF0HAh5cYGIAh9IIPC2Aw/7MPC/FhBDUYE6FRioUZGGFQCskWDZAA

**运行环境**
Windows 11，1600x900
[问题视频链接](https://www.bilibili.com/video/av112908398823972/)

**预期的正确表现**
能够正常识别出有关的内容

**Comment by LumiOwO** [comment]
方便发一下错误日志给我吗
路径是`C:\Users\<你的用户名>\Documents\LumiTracker\log\error.log`
感谢

**Comment by tiantianyigntao5** [comment]
> 方便发一下错误日志给我吗 路径是`C:\Users\<你的用户名>\Documents\LumiTracker\log\error.log` 感谢

[error.log](https://github.com/user-attachments/files/16504125/error.log)
这次是在全屏测试的

**Comment by tiantianyigntao5** [comment]
> 方便发一下错误日志给我吗 路径是`C:\Users\<你的用户名>\Documents\LumiTracker\log\error.log` 感谢

[error.log](https://github.com/user-attachments/files/16504140/error.log)
然后这次是在16:9比例窗口测试的

**Comment by LumiOwO** [comment]
我这边复现不了这个问题orz 
我看了视频，有点怀疑是显示屏dpi的问题，猜测是缩放设置导致了检测区域错位
能麻烦再看下显示屏的分辨率和缩放设置吗，在Windows的 设置 - 系统 - 屏幕 - 缩放和布局
![image](https://github.com/user-attachments/assets/addd03f2-42a5-450e-aed0-34a37f509cc3)

**Comment by LumiOwO** [comment]
关键是error.log很干净，没啥错误信息，应该就是检测区域错位了，但现在定位不到问题在哪 TAT
再求问下这几个问题：
1. 全屏下（无边框模式），可以正常识别吗
2. 有多个显示屏吗

**Comment by LumiOwO** [comment]
关键是error.log很干净，没啥错误信息，应该就是检测区域错位了，但现在定位不到问题在哪 TAT
再求问下这几个问题：
1. 全屏下（无边框模式），可以正常识别吗
2. 有多个显示屏吗
3. 有同时开其他的原神相关软件吗（我看你游戏内鼠标指针是蓝色的）

**Comment by LumiOwO** [comment]
可能是BitBlt设置的问题，试下这个解决办法
babalae/better-genshin-impact#92
我之后也把截屏方式的选项开放出来

**Comment by tiantianyigntao5** [comment]
问题已解决，感谢作者大大
